name: Deployment

env:
  IMAGE_NAME: react-image
  USER_NAME: rajapandian2003
  REPO_NAME: react-github-action
  VERSION: latest
  CONTAINER_NAME: react-container
  CONTAINER_PORT: 80
  HOST_PORT: 3000

on:
  workflow_run:
    workflows: ["sample CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Delete the old image
      run: docker rmi -f $IMAGE_NAME || true
    
    - name: Delete the old image
      run: docker rmi -f $USER_NAME/$REPO_NAME:$VERSION || true

    - name: Login to Docker
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: PUll the image
      run: sudo docker pull $USER_NAME/$REPO_NAME:$VERSION

    - name: Delete the old container
      run: docker rm -f $CONTAINER_NAME || true
    
    - name: Run Image
      run : sudo docker run -d -p $HOST_PORT:$CONTAINER_PORT --name $CONTAINER_NAME $USER_NAME/$REPO_NAME:$VERSION