name: Deployment

on:
  workflow_run:
    workflows: ["sample CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Delete the old image
      run: docker rmi -f react-image || true
    
    - name: Delete the old image
      run: docker rmi -f rajapandian2003/frontend-github-action:latest || true

    - name: Login to Docker
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: PUll the image
      run: sudo docker pull rajapandian2003/frontend-github-action:latest

    - name: Delete the old container
      run: docker rm -f react-container || true
    
    - name: Run Image
      run : sudo docker run -d -p 3000:80 --name react-container rajapandian2003/frontend-github-action:latest