name: sample CI

env:
  IMAGE_NAME: react-image
  USER_NAME: rajapandian2003
  REPO_NAME: frontend-github-action
  VERSION: latest

on: 
  push: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Build image
        run: |
          docker build -t $IMAGE_NAME .
          docker images
      
      - name: Tag the image
        run: |
          docker tag $IMAGE_NAME $USER_NAME/$REPO_NAME
          docker images
      
      - name: Push to Dockerhub
        run: docker push $USER_NAME/$REPO_NAME:$VERSION
